[package]
name = "libsolver"
version = "0.1.0"
authors = ["Sergey Pepyakin <s.pepyakin@gmail.com>"]

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
sudoku = "0.3.2"
error-chain = "0.11.0"
